"""
src/watchers/gmail_watcher.py — Gmail perception layer (Silver tier).

Polls Gmail for unread important messages every 120 seconds and writes
structured action cards to VAULT_PATH/Needs_Action/ for Claude to reason about.

Authentication: OAuth2 via google-auth-oauthlib.
  - Run `python scripts/setup_gmail_auth.py` once to generate the token file.
  - GMAIL_TOKEN_PATH      : path to the persisted OAuth2 token (JSON)
  - GMAIL_CREDENTIALS_PATH: path to the OAuth2 client secret file (from Google Cloud)

Idempotency:
  - Gmail message IDs are stored in the BaseWatcher state file between runs.
  - Reboots don't re-process already-seen messages.

Error philosophy (inherits from BaseWatcher):
  - Token expired / revoked  → AuthExpiredError  → user prompted to re-run setup
  - HTTP 429 / rate limit    → RateLimitError    → auto-retry with backoff
  - Connection failure       → NetworkError      → auto-retry with backoff
  - Malformed message body   → ParseError        → quarantine card written
"""

import logging
import os
import time
from pathlib import Path

from dotenv import load_dotenv

from src.exceptions import AuthExpiredError, NetworkError, ParseError, RateLimitError
from src.watchers.base_watcher import BaseWatcher

load_dotenv()

logger = logging.getLogger(__name__)

# Gmail query: unread messages marked as important
_GMAIL_QUERY = "is:unread is:important"


class GmailWatcher(BaseWatcher):
    """
    Silver-tier watcher: polls Gmail for unread important messages.

    Environment variables:
        GMAIL_TOKEN_PATH       Path to OAuth2 token JSON (generated by setup_gmail_auth.py).
        GMAIL_CREDENTIALS_PATH Path to OAuth2 client secret JSON (from Google Cloud Console).
        VAULT_PATH             Obsidian vault root.
    """

    def __init__(self, check_interval: int = 120):
        super().__init__(check_interval=check_interval)
        self._service = None  # Lazy-initialised on first poll

        self._token_path = Path(os.getenv("GMAIL_TOKEN_PATH", "credentials/gmail_token.json"))
        self._creds_path = Path(os.getenv("GMAIL_CREDENTIALS_PATH", "credentials/gmail_credentials.json"))

    # ── BaseWatcher interface ─────────────────────────────────────────────────

    def check_for_updates(self) -> list:
        """
        Fetch unread important Gmail messages not yet processed.
        Returns a list of Gmail message dicts (minimal — id + threadId).
        """
        service = self._get_service()
        try:
            result = service.users().messages().list(
                userId="me",
                q=_GMAIL_QUERY,
                maxResults=20,
            ).execute()
        except Exception as exc:
            self._translate_api_error(exc)

        messages = result.get("messages", [])
        return [m for m in messages if m["id"] not in self._processed_ids]

    def get_event_id(self, item: dict) -> str:
        """Stable ID: Gmail message ID (globally unique)."""
        return item["id"]

    def create_action_file(self, item: dict) -> Path:
        """
        Fetch full message details from Gmail and write a structured action card.
        Returns path of the written .md file.
        """
        service = self._get_service()
        try:
            msg = service.users().messages().get(
                userId="me",
                id=item["id"],
                format="full",
            ).execute()
        except Exception as exc:
            self._translate_api_error(exc)

        headers = {
            h["name"]: h["value"]
            for h in msg.get("payload", {}).get("headers", [])
        }
        snippet = msg.get("snippet", "").replace('"', "'")
        received = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        sender = headers.get("From", "Unknown")
        subject = headers.get("Subject", "No Subject")
        date_header = headers.get("Date", received)

        content = "\n".join([
            "---",
            "type: email",
            f"gmail_id: {item['id']}",
            f"from: \"{sender}\"",
            f"subject: \"{subject}\"",
            f"date_sent: \"{date_header}\"",
            f"received: {received}",
            "priority: high",
            "status: pending",
            "---",
            "",
            f"## Email: {subject}",
            "",
            f"**From**: {sender}",
            f"**Received**: {received}",
            "",
            "## Preview",
            "",
            snippet,
            "",
            "## Suggested Actions",
            "- [ ] Reply to sender",
            "- [ ] Forward to relevant party",
            "- [ ] Archive after processing",
        ])

        self.needs_action.mkdir(parents=True, exist_ok=True)
        card_path = self.needs_action / f"EMAIL_{item['id']}.md"
        card_path.write_text(content, encoding="utf-8")
        logger.info("Email action card written: %s", card_path.name)
        return card_path

    # ── Google API client (lazy init) ─────────────────────────────────────────

    def _get_service(self):
        """Return the Gmail API service, building it on first call."""
        if self._service is not None:
            return self._service

        try:
            from google.oauth2.credentials import Credentials
            from google.auth.transport.requests import Request
            from googleapiclient.discovery import build
        except ImportError as exc:
            raise AuthExpiredError(
                f"google-api-python-client not installed: {exc}",
                user_message="Gmail integration requires extra Python packages.",
                action_hint=(
                    "Run: pip install google-api-python-client google-auth-oauthlib\n"
                    "Then run: python scripts/setup_gmail_auth.py"
                ),
            ) from exc

        if not self._token_path.exists():
            raise AuthExpiredError(
                f"Gmail token not found at {self._token_path}",
                user_message="Gmail is not yet authorised.",
                action_hint="Run: python scripts/setup_gmail_auth.py",
            )

        try:
            creds = Credentials.from_authorized_user_file(str(self._token_path))
        except Exception as exc:
            raise AuthExpiredError(
                f"Could not load Gmail token: {exc}",
                user_message="The Gmail token file is corrupted or invalid.",
                action_hint="Delete the token file and run: python scripts/setup_gmail_auth.py",
            ) from exc

        # Refresh if expired
        if creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
                self._token_path.write_text(creds.to_json(), encoding="utf-8")
                logger.info("Gmail token refreshed automatically.")
            except Exception as exc:
                raise AuthExpiredError(
                    f"Gmail token refresh failed: {exc}",
                    user_message="Your Gmail authorisation has expired and could not be renewed.",
                    action_hint="Run: python scripts/setup_gmail_auth.py",
                ) from exc

        self._service = build("gmail", "v1", credentials=creds, cache_discovery=False)
        logger.info("Gmail API service initialised.")
        return self._service

    # ── Error translation ─────────────────────────────────────────────────────

    def _translate_api_error(self, exc: Exception) -> None:
        """Raise a typed WatcherError from a raw Google API exception."""
        err_str = str(exc).lower()
        status = getattr(getattr(exc, "resp", None), "status", None)

        if status in (401, 403) or "invalid_grant" in err_str or "unauthorized" in err_str:
            raise AuthExpiredError(
                f"Gmail API auth failure: {exc}",
                user_message="Gmail credentials have been revoked or expired.",
                action_hint=(
                    "Delete the token file and run: python scripts/setup_gmail_auth.py"
                ),
            ) from exc

        if status == 429 or "rate limit" in err_str or "quota" in err_str:
            raise RateLimitError(
                f"Gmail API rate limit: {exc}",
                retry_after=60,
            ) from exc

        if "connection" in err_str or "timeout" in err_str or "network" in err_str:
            raise NetworkError(f"Gmail API connection error: {exc}") from exc

        # Unknown — wrap as generic NetworkError so retry logic applies
        raise NetworkError(f"Gmail API error ({type(exc).__name__}): {exc}") from exc


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [GmailWatcher] %(levelname)s: %(message)s",
    )
    GmailWatcher().run()
